import {
  Injectable,
  NotFoundException,
  ForbiddenException,
} from '@nestjs/common';
import { OrderItemRepository } from '../repositories/order-item.repository';
import { OrderItem } from '../entities/order-item.entity';
import { CreateOrderItemDto } from '../dto/create-order-item.dto';

@Injectable()
export class OrderItemService {
  constructor(private readonly orderItemRepository: OrderItemRepository) {}

  async create(
    orderId: string,
    createDto: CreateOrderItemDto,
  ): Promise<OrderItem> {
    const item = new OrderItem({
      id: '', // ID will be generated by DB
      orderId,
      productId: createDto.productId,
      varientId: createDto.varientId,
      productName: createDto.productName,
      quantity: createDto.quantity,
      price: createDto.price,
      refundedQuantity: 0,
      refundedAmount: 0,
      refundStatus: 'NONE',
      createdAt: new Date(),
    });

    return this.orderItemRepository.create(item);
  }

  async findOne(id: string, orderId?: string): Promise<OrderItem> {
    const item = await this.orderItemRepository.findOne(id);
    if (!item) {
      throw new NotFoundException('Order item not found');
    }
    if (orderId && item.orderId !== orderId) {
      throw new ForbiddenException('Item does not belong to this order');
    }
    return item;
  }

  async findByOrderId(orderId: string): Promise<OrderItem[]> {
    return this.orderItemRepository.findByOrderId(orderId);
  }

  async update(orderId: string, item: OrderItem): Promise<OrderItem> {
    const existingItem = await this.findOne(item.id, orderId);
    return this.orderItemRepository.update({
      ...existingItem,
      ...item,
    });
  }

  async remove(id: string, orderId: string): Promise<OrderItem> {
    const item = await this.findOne(id, orderId);
    return this.orderItemRepository.remove(item.id);
  }
}
